[package]
name = "mit-lint"
version = "3.2.3"
edition = "2018"
authors = ["Billie Thompson <billie+mit-lint@billiecodes.com>"]
license = "CC0-1.0"
description = "Lints for commits parsed with mit-commit."
categories = ["development-tools"]
keywords = ["git", "commit", "lints"]
readme = "README.md"
repository = "https://github.com/PurpleBooth/mit-lint"

[dependencies]
miette = { version = "5.5.0", features = ["fancy"] }
thiserror = "1.0.39"
mit-commit = "3.1.6"
regex = "1.7.1"
strum = { version = "0.24.1", features = ["derive"] }
toml = "0.7.2"
futures = "0.3.26"
lazy_static = "1.4.0"
quickcheck = "1.0.3"
strum_macros = "0.24.3"

[dependencies.serde]
version = "1.0.153"
features = ["derive"]

[dev-dependencies]
criterion = { version = "0.4.0", features = ["async_tokio"] }
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
tokio = { version = "1.26.0", features = ["full"] }

[[bench]]
name = "linting"
harness = false
[[bench]]
name = "async_linting"
harness = false
