[package]
name = "mit-lint"
version = "3.3.0"
edition = "2018"
authors = ["Billie Thompson <billie+mit-lint@billiecodes.com>"]
license = "CC0-1.0"
description = "Lints for commits parsed with mit-commit."
categories = ["development-tools"]
keywords = ["git", "commit", "lints"]
readme = "README.md"
repository = "https://github.com/PurpleBooth/mit-lint"

[dependencies]
ahash = { version = "0.7.7, ||, ^0", default-features = false, features = [] }
miette = { version = "7.2.0", features = ["fancy"] }
thiserror = "2.0.11"
mit-commit = "3.2.0"
regex = "1.11.0"
strum = { version = "0.27.1", features = ["derive"] }
toml = "0.8.16"
futures = "0.3.30"
quickcheck = "1.0.3"
strum_macros = "0.27.1"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["async_tokio"] }
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
tokio = { version = "1.43.1", features = ["full"] }

[[bench]]
name = "linting"
harness = false
[[bench]]
name = "async_linting"
harness = false
