[package]
name = "mit-lint"
version = "0.1.2"
edition = "2018"
authors = [ "Billie Thompson <billie+mit-lint@billiecodes.com>" ]
license = "CC0-1.0"
description = "Lints for commits parsed with mit-commit."
categories = [ "development-tools" ]
keywords = [ "git", "commit", "lints" ]
readme = "README.md"
repository = "https://github.com/PurpleBooth/mit-lint"

[dependencies]
thiserror = "1.0.29"
mit-commit = "1.29.8"
regex = "1.5.4"
indoc = "1.0.3"
toml = "0.5.8"
lazy_static = "1.4.0"

[dependencies.serde]
version = "1.0.125"
features = [ "derive" ]

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "linting"
harness = false