[package]
name = "mit-lint"
version = "3.0.7"
edition = "2018"
authors = ["Billie Thompson <billie+mit-lint@billiecodes.com>"]
license = "CC0-1.0"
description = "Lints for commits parsed with mit-commit."
categories = ["development-tools"]
keywords = ["git", "commit", "lints"]
readme = "README.md"
repository = "https://github.com/PurpleBooth/mit-lint"

[dependencies]
miette = { version = "5.1.0", features = ["fancy"] }
thiserror = "1.0.31"
mit-commit = "3.1.1"
regex = "1.6.0"
strum = { version = "0.24.1", features = ["derive"] }
toml = "0.5.9"
futures = "0.3.21"
lazy_static = "1.4.0"
quickcheck = "1.0.3"
strum_macros = "0.24.2"

[dependencies.serde]
version = "1.0.138"
features = ["derive"]

[dev-dependencies]
criterion = { version = "0.3.5", features = ["async_tokio"] }
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
tokio = { version = "1.19.2", features = ["full"] }

[[bench]]
name = "linting"
harness = false
[[bench]]
name = "async_linting"
harness = false
