[package]
name = "mit-lint"
version = "2.2.3"
edition = "2018"
authors = ["Billie Thompson <billie+mit-lint@billiecodes.com>"]
license = "CC0-1.0"
description = "Lints for commits parsed with mit-commit."
categories = ["development-tools"]
keywords = ["git", "commit", "lints"]
readme = "README.md"
repository = "https://github.com/PurpleBooth/mit-lint"

[dependencies]
miette = { version = "3.1.0", features = ["fancy"] }
thiserror = "1.0.30"
mit-commit = "1.33.1"
regex = "1.5.4"
strum = { version = "0.22.0", features = ["derive"] }
toml = "0.5.8"
futures = "0.3.17"
lazy_static = "1.4.0"
quickcheck = "1.0.3"
strum_macros = "0.22.0"

[dependencies.serde]
version = "1.0.130"
features = ["derive"]

[dev-dependencies]
criterion = { version = "0.3.5", features = ["async_tokio"] }
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
tokio = { version = "1.12.0", features = ["full"] }

[[bench]]
name = "linting"
harness = false
