tag_prefix = "v"
from_latest_tag = true
ignore_merge_commits = true
branch_whitelist = ["main", "HEAD"]
pre_bump_hooks = [
    "cargo set-version --workspace {{version}}",
    "cargo build --release",
]
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]

[commit_types]
