---
when:
  event: [push, pull_request]
  path:
    exclude: [CHANGELOG.md]
matrix:
  RUST: [stable, beta, nightly]
steps:
  test:
    image: rust@sha256:087fe682ef35ecac5b110dbf35cafade2cbd487f8a86e9390203f77f962887cf
    environment:
      CARGO_TERM_COLOR: always
    commands: [rustup default $RUST, cargo test]
  audit:
    image: woodpeckerci/plugin-trivy@sha256:27a5d91ef8ca9da29540e4ddff43001f7ec44325f5d0ecfcfbe450cd99394302
    commands: [trivy fs .]
